class LifeMateHealthFact {
  const LifeMateHealthFact({
    required this.category,
    required this.text,
  });

  final String category;
  final String text;
}

/// Short, general-purpose wellbeing prompts shown only while account bootstrap
/// is genuinely running. They are intentionally non-diagnostic and do not
/// replace advice from a clinician who knows the user's medical history.
const List<LifeMateHealthFact> lifeMateHealthFacts = [
  LifeMateHealthFact(category: 'آب و بدن', text: 'یک لیوان آب کنار محل کار یا استراحت، یادآوری نوشیدن آب را ساده‌تر می‌کند.'),
  LifeMateHealthFact(category: 'آب و بدن', text: 'رنگ بسیار تیره ادرار می‌تواند نشانه نیاز به مایعات بیشتر باشد؛ شرایط پزشکی خاص را با پزشک بررسی کنید.'),
  LifeMateHealthFact(category: 'آب و بدن', text: 'در هوای گرم و هنگام فعالیت بدنی، نیاز بدن به مایعات معمولاً بیشتر می‌شود.'),
  LifeMateHealthFact(category: 'آب و بدن', text: 'میوه‌ها و سبزی‌ها علاوه بر مواد مغذی، بخشی از آب روزانه بدن را هم تأمین می‌کنند.'),
  LifeMateHealthFact(category: 'آب و بدن', text: 'نوشیدنی‌های بسیار شیرین را می‌توان با آب، دوغ کم‌نمک یا نوشیدنی بدون شکر جایگزین کرد.'),
  LifeMateHealthFact(category: 'خواب', text: 'بیدارشدن در ساعت تقریباً ثابت، به منظم‌شدن ساعت زیستی بدن کمک می‌کند.'),
  LifeMateHealthFact(category: 'خواب', text: 'نور زیاد صفحه‌نمایش نزدیک زمان خواب می‌تواند به خواب‌رفتن را دشوارتر کند.'),
  LifeMateHealthFact(category: 'خواب', text: 'اتاق نسبتاً خنک، تاریک و آرام برای بسیاری از افراد خواب راحت‌تری ایجاد می‌کند.'),
  LifeMateHealthFact(category: 'خواب', text: 'کافئین عصرگاهی در بعضی افراد کیفیت خواب شبانه را کاهش می‌دهد.'),
  LifeMateHealthFact(category: 'خواب', text: 'یک روتین کوتاه مثل مسواک، نور کم و چند نفس آرام، به مغز پیام نزدیک‌شدن زمان خواب می‌دهد.'),
  LifeMateHealthFact(category: 'خواب', text: 'چرت طولانی یا دیرهنگام ممکن است خواب شب را به‌هم بزند؛ واکنش بدن خودتان را بررسی کنید.'),
  LifeMateHealthFact(category: 'خواب', text: 'اگر خرخر شدید، قطع تنفس یا خواب‌آلودگی روزانه مداوم دارید، ارزیابی پزشکی مهم است.'),
  LifeMateHealthFact(category: 'خواب', text: 'ثبت زمان خواب و بیداری برای چند روز می‌تواند الگوی واقعی خواب را روشن‌تر کند.'),
  LifeMateHealthFact(category: 'خواب', text: 'وعده بسیار سنگین درست پیش از خواب ممکن است باعث ناراحتی و اختلال خواب شود.'),
  LifeMateHealthFact(category: 'خواب', text: 'نور طبیعی صبحگاهی می‌تواند به تنظیم چرخه خواب و بیداری کمک کند.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'نیمی از بشقاب را می‌توان با سبزی‌ها و سالاد متنوع‌تر کرد.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'تنوع رنگ در میوه و سبزی معمولاً به معنی دریافت طیف متنوع‌تری از مواد مغذی است.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'حبوبات منبع خوب فیبر و پروتئین گیاهی هستند و می‌توانند چند وعده در هفته جای گوشت را بگیرند.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'غلات کامل معمولاً فیبر بیشتری از انواع کاملاً تصفیه‌شده دارند.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'آجیل و دانه‌ها مغذی‌اند، اما به دلیل انرژی بالا بهتر است مقدار مصرفشان متعادل باشد.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'خواندن برچسب محصول کمک می‌کند مقدار نمک، شکر افزوده و چربی اشباع را مقایسه کنید.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'آهسته‌تر غذاخوردن فرصت بیشتری برای درک سیری به بدن می‌دهد.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'برنامه‌ریزی یک میان‌وعده ساده مثل میوه، احتمال انتخاب خوراکی بسیار شیرین را کمتر می‌کند.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'ماهی، حبوبات، تخم‌مرغ و گوشت کم‌چرب می‌توانند منابع متنوع پروتئین باشند.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'روش‌هایی مثل بخارپز، تنوری و کبابی معمولاً به روغن کمتری از سرخ‌کردن عمیق نیاز دارند.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'نمکدان را از سفره دور کنید و برای طعم از سبزی‌های معطر و ادویه‌های مناسب استفاده کنید.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'ماست ساده همراه میوه می‌تواند جایگزین کم‌شکرتری برای بعضی دسرها باشد.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'خرید با فهرست از قبل نوشته‌شده، انتخاب‌های برنامه‌ریزی‌نشده را کمتر می‌کند.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'حجم مناسب غذا برای هر فرد متفاوت است؛ به گرسنگی، سیری و شرایط پزشکی توجه کنید.'),
  LifeMateHealthFact(category: 'تغذیه', text: 'شستن دست‌ها و نگهداری درست مواد غذایی، بخش مهمی از سلامت تغذیه است.'),
  LifeMateHealthFact(category: 'حرکت', text: 'چند دقیقه راه‌رفتن در طول روز هم از بی‌تحرکی کامل بهتر است.'),
  LifeMateHealthFact(category: 'حرکت', text: 'فعالیتی را انتخاب کنید که از آن لذت می‌برید؛ تداوم از شدت مقطعی مهم‌تر است.'),
  LifeMateHealthFact(category: 'حرکت', text: 'گرم‌کردن تدریجی پیش از فعالیت و سردکردن پس از آن، به سازگاری بدن کمک می‌کند.'),
  LifeMateHealthFact(category: 'حرکت', text: 'تمرین قدرتی متناسب با توان فرد می‌تواند به حفظ عضله و عملکرد روزمره کمک کند.'),
  LifeMateHealthFact(category: 'حرکت', text: 'تمرین تعادل برای سالمندان می‌تواند بخشی از برنامه پیشگیری از زمین‌خوردن باشد.'),
  LifeMateHealthFact(category: 'حرکت', text: 'نشستن طولانی را با وقفه‌های کوتاه ایستادن یا کشش ملایم قطع کنید.'),
  LifeMateHealthFact(category: 'حرکت', text: 'کفش مناسب و سطح امن، احتمال آسیب هنگام پیاده‌روی را کمتر می‌کند.'),
  LifeMateHealthFact(category: 'حرکت', text: 'افزایش فعالیت بهتر است تدریجی باشد، مخصوصاً پس از یک دوره کم‌تحرکی.'),
  LifeMateHealthFact(category: 'حرکت', text: 'درد قفسه سینه، تنگی نفس غیرعادی یا سرگیجه هنگام ورزش نیازمند توقف و ارزیابی است.'),
  LifeMateHealthFact(category: 'حرکت', text: 'کارهای روزمره مثل پله، خرید و باغبانی هم می‌توانند بخشی از فعالیت روزانه باشند.'),
  LifeMateHealthFact(category: 'حرکت', text: 'یک قرار پیاده‌روی خانوادگی، هم حرکت و هم ارتباط عاطفی را تقویت می‌کند.'),
  LifeMateHealthFact(category: 'حرکت', text: 'کشش نباید با درد تیز همراه باشد؛ دامنه راحت و کنترل‌شده را انتخاب کنید.'),
  LifeMateHealthFact(category: 'قلب و عروق', text: 'اندازه‌گیری فشار خون باید در حالت آرام و با کاف مناسب بازو انجام شود.'),
  LifeMateHealthFact(category: 'قلب و عروق', text: 'ثبت زمان و شرایط اندازه‌گیری فشار خون، تفسیر روند را برای پزشک آسان‌تر می‌کند.'),
  LifeMateHealthFact(category: 'قلب و عروق', text: 'کاهش مصرف نمک برای بسیاری از افراد بخشی از مراقبت از فشار خون است.'),
  LifeMateHealthFact(category: 'قلب و عروق', text: 'ترک دخانیات از مهم‌ترین قدم‌ها برای سلامت قلب و ریه است.'),
  LifeMateHealthFact(category: 'قلب و عروق', text: 'درد جدید قفسه سینه یا علائم شدید و ناگهانی را نباید با توصیه‌های عمومی مدیریت کرد؛ کمک فوری بگیرید.'),
  LifeMateHealthFact(category: 'قلب و عروق', text: 'فعالیت منظم، خواب کافی و تغذیه متعادل در کنار درمان پزشکی از سلامت قلب حمایت می‌کنند.'),
  LifeMateHealthFact(category: 'دارو', text: 'دارو را دقیقاً طبق دستور پزشک یا داروساز مصرف کنید و دوز را خودسرانه تغییر ندهید.'),
  LifeMateHealthFact(category: 'دارو', text: 'فهرست به‌روز داروها، مکمل‌ها و حساسیت‌ها را همراه داشته باشید.'),
  LifeMateHealthFact(category: 'دارو', text: 'برای هر دارو بدانید چرا مصرف می‌شود، چه زمانی باید خورده شود و عارضه مهم آن چیست.'),
  LifeMateHealthFact(category: 'دارو', text: 'داروها را دور از دسترس کودکان و مطابق شرایط درج‌شده روی بسته نگهداری کنید.'),
  LifeMateHealthFact(category: 'دارو', text: 'داروی تاریخ‌گذشته یا بدون برچسب مشخص را مصرف نکنید.'),
  LifeMateHealthFact(category: 'دارو', text: 'پیش از افزودن مکمل یا داروی بدون نسخه، احتمال تداخل را با پزشک یا داروساز بررسی کنید.'),
  LifeMateHealthFact(category: 'دارو', text: 'اگر یک نوبت دارو فراموش شد، دستور همان دارو را بررسی کنید؛ دوبرابرکردن دوز همیشه درست نیست.'),
  LifeMateHealthFact(category: 'دارو', text: 'جعبه هفتگی دارو برای بعضی افراد مفید است، به شرطی که دارو برای نگهداری خارج بسته مناسب باشد.'),
  LifeMateHealthFact(category: 'دارو', text: 'یادآور زمانی زمانی مؤثرتر است که با یک عادت ثابت روزانه پیوند بخورد.'),
  LifeMateHealthFact(category: 'دارو', text: 'در مراجعه پزشکی، همه داروهای تجویزی، بدون نسخه و گیاهی را اعلام کنید.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'برنامه چکاپ به سن، جنس، سابقه خانوادگی و وضعیت پزشکی هر فرد بستگی دارد.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'تاریخ واکسن‌ها را ثبت کنید تا یادآوری نوبت‌های بعدی آسان‌تر شود.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'غربالگری‌ها زمانی ارزشمندترند که طبق توصیه معتبر و متناسب با ریسک فرد انجام شوند.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'نتایج آزمایش را همراه تاریخ و محدوده مرجع نگهداری کنید تا روندها قابل مقایسه باشند.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'تغییرات پایدار و غیرعادی بدن را ثبت و در زمان مناسب با پزشک مطرح کنید.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'معاینه دندان و مراقبت منظم دهان بخشی از سلامت عمومی است.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'بررسی بینایی و شنوایی برای حفظ استقلال و ایمنی سالمندان اهمیت دارد.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'پیش از ویزیت، سه سؤال اصلی خود را بنویسید تا چیزی فراموش نشود.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'یک همراه مورد اعتماد می‌تواند در ویزیت‌های پیچیده به یادداشت‌برداری کمک کند.'),
  LifeMateHealthFact(category: 'چکاپ', text: 'توصیه‌های پزشکی را با تاریخ، مقدار و زمان پیگیری در یک برنامه روشن ثبت کنید.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'چند نفس آهسته و عمیق می‌تواند در لحظه‌های تنش به آرام‌ترشدن کمک کند.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'ارتباط منظم با یک فرد قابل اعتماد، از احساس تنهایی کم می‌کند.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'استراحت کوتاه مراقب، بخشی از مراقبت مسئولانه است و نشانه کم‌کاری نیست.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'نوشتن نگرانی‌ها می‌تواند ذهن را برای تصمیم‌گیری منظم‌تر کند.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'اگر غم، اضطراب یا بی‌انگیزگی پایدار بر زندگی روزمره اثر گذاشته، کمک تخصصی ارزشمند است.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'مقایسه مداوم خود با تصاویر ایده‌آل شبکه‌های اجتماعی می‌تواند حال روانی را ضعیف کند.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'یک فعالیت کوچک لذت‌بخش را از قبل در برنامه روزانه قرار دهید.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'تقسیم یک کار بزرگ به قدم‌های بسیار کوچک، شروع‌کردن را آسان‌تر می‌کند.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'بیان روشن نیازها و مرزها از فرسودگی در روابط مراقبتی پیشگیری می‌کند.'),
  LifeMateHealthFact(category: 'سلامت روان', text: 'در بحران روانی یا خطر آسیب، از خدمات فوری و افراد قابل اعتماد کمک بگیرید.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'مسئولیت‌های مراقبت را شفاف تقسیم کنید تا همه بدانند چه کاری بر عهده چه کسی است.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'یک فهرست مشترک از داروها، شماره پزشکان و تماس‌های ضروری آماده کنید.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'پرسیدن «چه کمکی برایت مفید است؟» معمولاً بهتر از حدس‌زدن نیاز فرد است.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'استقلال فرد را تا حد امن حفظ کنید و کارهایی را که می‌تواند انجام دهد از او نگیرید.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'در کنار پیگیری درمان، زمانی برای گفت‌وگوی عادی و بدون موضوع پزشکی بگذارید.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'تغییر ناگهانی رفتار، هوشیاری یا توانایی انجام کارهای روزمره را جدی بگیرید.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'برنامه جایگزین برای زمانی که مراقب اصلی در دسترس نیست، اضطراب را کمتر می‌کند.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'داده سلامت را فقط با رضایت فرد و در محدوده لازم به اشتراک بگذارید.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'تشویق صادقانه پس از انجام برنامه درمانی می‌تواند از سرزنش مؤثرتر باشد.'),
  LifeMateHealthFact(category: 'مراقبت خانوادگی', text: 'برای سالمند، نوشته درشت، کنتراست مناسب و دستورهای کوتاه استفاده را آسان‌تر می‌کند.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'یک عادت جدید را به کاری که همیشه انجام می‌دهید وصل کنید؛ مثلاً دارو بعد از مسواک.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'هدف‌های کوچک و قابل اندازه‌گیری معمولاً پایدارتر از تصمیم‌های بسیار بزرگ هستند.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'محیط را طوری بچینید که انتخاب سالم، ساده‌ترین انتخاب باشد.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'پیشرفت را هفتگی بررسی کنید؛ نوسان یک روز به‌تنهایی تصویر کاملی نمی‌دهد.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'جشن‌گرفتن قدم‌های کوچک به تداوم رفتار کمک می‌کند.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'روزهای ناموفق بخشی از مسیرند؛ به‌جای رهاکردن، از نوبت بعدی ادامه دهید.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'یادآور خوب باید در زمان، مکان و با متن روشن به کاربر کمک کند.'),
  LifeMateHealthFact(category: 'عادت‌های سالم', text: 'برای تصمیم‌های تکراری مثل وعده صبحانه یا زمان پیاده‌روی، الگوی ثابت بسازید.'),
  LifeMateHealthFact(category: 'ایمنی', text: 'راهروها و مسیرهای رفت‌وآمد خانه را روشن و بدون مانع نگه دارید.'),
  LifeMateHealthFact(category: 'ایمنی', text: 'شماره‌های ضروری و اطلاعات پزشکی مهم را در جایی قابل دسترس نگه دارید.'),
  LifeMateHealthFact(category: 'ایمنی', text: 'علائم شدید، ناگهانی یا رو به بدترشدن نیازمند ارزیابی حرفه‌ای هستند، نه جست‌وجوی طولانی در اینترنت.'),
  LifeMateHealthFact(category: 'ایمنی', text: 'برای توصیه‌های سلامت آنلاین، منبع، تاریخ و تناسب آن با شرایط خود را بررسی کنید.'),
];