Future<String> enqueueTreatmentPlanEdit({
  required String environmentId,
  required String accountId,
  required String personId,
  required String treatmentPlanId,
  required int version,
  required int medicationVersion,
  required String medicationName,
  String? strengthText,
  String? form,
  required String doseText,
  String? instructions,
  required DateTime startDate,
  DateTime? endDate,
  required String timeZone,
  required List<Map<String, String>> schedules,
  required int patientReminderMinutesBefore,
  required int caregiverReminderMinutesBefore,
  required String status,
  required String mutationId,
  Object? localStore,
}) => Future<String>.error(
  UnsupportedError('Protected offline health execution is unavailable on web.'),
);
