import 'package:flutter_test/flutter_test.dart';
import 'package:caremate/services/companion_care_engine.dart';

void main(){const engine=CompanionCareEngine();final now=DateTime.utc(2026,8,27,12);
  test('no exact scope means no personalized guidance',(){expect(engine.select(phaseAllowed:false,wellbeingAllowed:false,cycleDay:4,mood:'low',energyLevel:1,guidanceHistory:const[],supportActions:const[],locale:'fa',nowUtc:now),isNull);});
  test('wellbeing scope can select low energy without clinical inference',(){final value=engine.select(phaseAllowed:false,wellbeingAllowed:true,cycleDay:null,mood:null,energyLevel:2,guidanceHistory:const[],supportActions:const[],locale:'fa',nowUtc:now);expect(value?.category,'energy');expect(value?.message,contains('بدون حدس'));});
  test('global cooldown suppresses repeated guidance',(){final value=engine.select(phaseAllowed:true,wellbeingAllowed:false,cycleDay:3,mood:null,energyLevel:null,guidanceHistory:[CompanionGuidanceHistoryItem(guidanceId:'other',shownAtUtc:now.subtract(const Duration(hours:2)))],supportActions:const[],locale:'en',nowUtc:now);expect(value,isNull);});
  test('recent support action deduplicates matching suggestion',(){final value=engine.select(phaseAllowed:true,wellbeingAllowed:false,cycleDay:3,mood:null,energyLevel:null,guidanceHistory:const[],supportActions:[CompanionSupportActionHistoryItem(actionType:'CheckIn',performedAtUtc:now.subtract(const Duration(hours:2)))],locale:'en',nowUtc:now);expect(value,isNull);});
  test('locale is versioned Persian or English',(){final fa=engine.select(phaseAllowed:true,wellbeingAllowed:false,cycleDay:3,mood:null,energyLevel:null,guidanceHistory:const[],supportActions:const[],locale:'fa-IR',nowUtc:now);final en=engine.select(phaseAllowed:true,wellbeingAllowed:false,cycleDay:3,mood:null,energyLevel:null,guidanceHistory:const[],supportActions:const[],locale:'en-US',nowUtc:now);expect(fa?.contentVersion,CompanionCareEngine.contentVersion);expect(fa?.locale,'fa');expect(en?.locale,'en');expect(fa?.message,isNot(equals(en?.message)));});
}
