import { json } from "./http.ts";
import { enforceRateLimit } from "./security.ts";
import { supportAttachmentMaximumBytes, type createSupportAttachmentRuntime } from "./support_attachment_storage.ts";
import { ApiError, readJsonObject } from "./validation.ts";
import type { createSupportConversationStore } from "./support_conversations.ts";
type Store=ReturnType<typeof createSupportConversationStore>; type AttachmentRuntime=ReturnType<typeof createSupportAttachmentRuntime>;
export function createSupportConversationRouteHandler(store:Store,attachments?:AttachmentRuntime){return async(input:{request:Request;path:string;appUserId:string}):Promise<Response|null>=>{const {request,path,appUserId}=input;
 if(request.method==="GET"&&path==="/api/v1/support/conversations"){enforceRateLimit(`support-inbox:${appUserId}`,120,60*60_000);const url=new URL(request.url);return json({items:await store.inbox(appUserId,boundedInboxLimit(url.searchParams.get("limit")))});}
 if(request.method==="POST"&&path==="/api/v1/support/conversations"){enforceRateLimit(`support-open:${appUserId}`,5,24*60*60_000);const body=await readJsonObject(request);return json(await store.open(appUserId,{productCode:optionalProductCode(body.productCode),category:optionalCategory(body.category)??"general",body:requiredMessage(body.body),clientMessageId:requiredUuid(body.clientMessageId)}),201);}
 const upload=path.match(/^\/api\/v1\/support\/conversations\/([0-9a-f-]{36})\/messages\/([0-9a-f-]{36})\/attachments$/i);if(request.method==="PUT"&&upload){if(!attachments)throw unavailable();enforceRateLimit(`support-attachment:${appUserId}`,20,60*60_000);const ticketId=requiredUuid(upload[1]),messageId=requiredUuid(upload[2]),fileName=requiredFileName(request.headers.get("x-file-name"));const declared=Number(request.headers.get("content-length")??0);if(Number.isFinite(declared)&&declared>supportAttachmentMaximumBytes)throw new ApiError(413,"support_attachment_too_large","Attachment must be no larger than 10 MB.");const bytes=new Uint8Array(await request.arrayBuffer());const accountId=await store.accountIdForAppUser(appUserId);const uploaded=await attachments.upload(accountId,ticketId,messageId,bytes,request.headers.get("content-type")??"");const sha256=await sha256Hex(bytes);let registered:Record<string,unknown>;try{registered=await store.registerAttachment(appUserId,{ticketId,messageId,fileName,contentType:uploaded.contentType,sizeBytes:bytes.byteLength,objectPath:uploaded.objectPath,sha256});}catch(e){await attachments.remove(uploaded.objectPath).catch(()=>undefined);throw e;}const attachmentId=requiredResultUuid(registered.attachmentId);const scan=await attachments.scan(bytes,uploaded.contentType,fileName);const finalized=await store.finalizeAttachmentScan(appUserId,attachmentId,scan.status,scan.reasonCode);if(scan.status!=="Available")await attachments.remove(uploaded.objectPath).catch(()=>undefined);return json({attachmentId,messageId,scanStatus:String(finalized.scanStatus??scan.status),downloadable:scan.status==="Available"},scan.status==="Available"?201:202);}
 const download=path.match(/^\/api\/v1\/support\/conversations\/([0-9a-f-]{36})\/attachments\/([0-9a-f-]{36})\/download$/i);if(request.method==="GET"&&download){if(!attachments)throw unavailable();enforceRateLimit(`support-attachment-download:${appUserId}`,60,60*60_000);const available=await store.getAttachmentDownload(appUserId,requiredUuid(download[1]),requiredUuid(download[2]));return json({attachmentId:available.attachmentId,fileName:available.fileName,contentType:available.contentType,sizeBytes:available.sizeBytes,signedUrl:await attachments.signedDownload(available.objectPath),expiresInSeconds:600});}
 const match=path.match(/^\/api\/v1\/support\/conversations\/([0-9a-f-]{36})(?:\/(messages|read))?$/i);if(!match)return null;const ticketId=requiredUuid(match[1]),suffix=match[2]??null;
 if(request.method==="GET"&&suffix===null){const url=new URL(request.url),beforeAt=optionalTimestamp(url.searchParams.get("beforeAt")),afterAt=optionalTimestamp(url.searchParams.get("afterAt"));if(beforeAt&&afterAt)throw new ApiError(400,"support_cursor_conflict","Use either beforeAt or afterAt, not both.");const items=await store.list(appUserId,ticketId,beforeAt,afterAt,boundedLimit(url.searchParams.get("limit")));return json({items,polling:{afterAt:items.length===0?afterAt:items[items.length-1].createdAtUtc}});}
 if(request.method==="POST"&&suffix==="messages"){enforceRateLimit(`support-send:${appUserId}`,60,60*60_000);const body=await readJsonObject(request);return json(await store.send(appUserId,ticketId,{body:requiredMessage(body.body),clientMessageId:requiredUuid(body.clientMessageId)}),201);}
 if(request.method==="POST"&&suffix==="read"){const body=await readJsonObject(request);return json(await store.markRead(appUserId,ticketId,requiredUuid(body.messageId)));}return null;};}
function requiredUuid(v:unknown):string{if(typeof v!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw new ApiError(400,"invalid_uuid","Identifier is invalid.");return v.toLowerCase();}function requiredResultUuid(v:unknown):string{if(typeof v!=="string")throw new Error("support_attachment_result_invalid");return requiredUuid(v);}function requiredMessage(v:unknown):string{if(typeof v!=="string")throw new ApiError(400,"support_message_invalid","Message is invalid.");const t=v.trim();if(!t||t.length>4000||new TextEncoder().encode(t).byteLength>12000)throw new ApiError(400,"support_message_invalid","Message is invalid.");return t;}function requiredFileName(v:string|null):string{const n=v?.trim()??"";if(!n||n.length>180||/[\\/\u0000-\u001f]/.test(n))throw new ApiError(400,"support_attachment_name_invalid","Attachment file name is invalid.");return n;}function optionalProductCode(v:unknown):string|null{if(v==null||v==="")return null;if(typeof v!=="string")throw new ApiError(400,"support_product_invalid","Support product is invalid.");const r=v.trim().toLowerCase();if(!r||r.length>64||!/^[a-z0-9][a-z0-9_.:-]*$/.test(r))throw new ApiError(400,"support_product_invalid","Support product is invalid.");return r;}function optionalCategory(v:unknown):string|null{if(v==null||v==="")return null;if(typeof v!=="string")throw new ApiError(400,"support_category_invalid","Support category is invalid.");const r=v.trim().toLowerCase();if(!/^[a-z0-9_-]{1,64}$/.test(r))throw new ApiError(400,"support_category_invalid","Support category is invalid.");return r;}function optionalTimestamp(v:string|null):string|null{if(v==null||v==="")return null;const d=new Date(v);if(!Number.isFinite(d.getTime()))throw new ApiError(400,"invalid_timestamp","Timestamp is invalid.");return d.toISOString();}function boundedLimit(v:string|null):number{if(v==null||v==="")return 50;if(!/^\d{1,3}$/.test(v))throw new ApiError(400,"invalid_page_size","Page size is invalid.");const n=Number(v);if(n<1||n>100)throw new ApiError(400,"invalid_page_size","Page size is invalid.");return n;}function boundedInboxLimit(v:string|null):number{if(v==null||v==="")return 20;if(!/^\d{1,2}$/.test(v))throw new ApiError(400,"invalid_page_size","Page size is invalid.");const n=Number(v);if(n<1||n>50)throw new ApiError(400,"invalid_page_size","Page size is invalid.");return n;}async function sha256Hex(bytes:Uint8Array):Promise<string>{const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,"0")).join("");}function unavailable():ApiError{return new ApiError(503,"support_attachment_runtime_unavailable","Attachment service is temporarily unavailable.");}
