from pathlib import Path

root = Path(__file__).resolve().parents[2]
path = root / "packages/lifemate_client/test/lifemate_edit_api_test.dart"
text = path.read_text(encoding="utf-8")
old = """      httpClient: MockClient((request) async {\n        requests.add(request);\n        if (request.method == 'GET') {\n          return http.Response(\n            jsonEncode({\n              'id': 'event-1',\n              'eventType': 'appointment',\n              'title': 'چکاپ زنان',\n              'providerName': 'سارا راد',\n              'centerName': 'مرکز الوند',\n              'scheduledLocalDate': '2026-08-08',\n              'scheduledLocalTime': '18:30',\n              'timeZone': 'Asia/Tehran',\n              'patientReminderMinutesBefore': 30,\n              'caregiverReminderMinutesBefore': 60,\n              'version': 3,\n              'status': 'missed',\n            }),\n            200,\n          );\n        }\n        return http.Response(\n          jsonEncode({'id': 'event-1', 'status': 'completed', 'version': 4}),\n          200,\n        );\n      }),\n"""
new = """      httpClient: MockClient((request) async {\n        requests.add(request);\n        if (request.method == 'GET') {\n          return http.Response(\n            jsonEncode({\n              'id': 'event-1',\n              'eventType': 'appointment',\n              'title': 'چکاپ زنان',\n              'providerName': 'سارا راد',\n              'centerName': 'مرکز الوند',\n              'scheduledLocalDate': '2026-08-08',\n              'scheduledLocalTime': '18:30',\n              'timeZone': 'Asia/Tehran',\n              'patientReminderMinutesBefore': 30,\n              'caregiverReminderMinutesBefore': 60,\n              'version': 3,\n              'status': 'missed',\n            }),\n            200,\n            headers: {'content-type': 'application/json; charset=utf-8'},\n          );\n        }\n        return http.Response(\n          jsonEncode({'id': 'event-1', 'status': 'completed', 'version': 4}),\n          200,\n          headers: {'content-type': 'application/json; charset=utf-8'},\n        );\n      }),\n"""
if text.count(old) != 1:
    raise SystemExit(f"expected one status-test mock block, found {text.count(old)}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
