name: wellmate
description: WellMate Patient App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  google_fonts: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
