name: cocoonmate_module
description: Reusable CocoonMate product experience for LifeMate hosts.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lifemate_client:
    path: ../lifemate_client
  lifemate_ui:
    path: ../lifemate_ui
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
