import 'package:flutter/material.dart';
import 'package:lifemate_client/lifemate_client.dart';

class LifeMateCompanionCareScreen extends StatefulWidget {
  const LifeMateCompanionCareScreen({super.key,required this.apiClient,this.companionApi,this.accent=const Color(0xFF4D8EF7),this.background=const Color(0xFFF6F9FF)});
  final LifeMateApiClient apiClient;
  final LifeMateCompanionCareApi? companionApi;
  final Color accent, background;
  @override State<LifeMateCompanionCareScreen> createState()=>_LifeMateCompanionCareScreenState();
}

class _LifeMateCompanionCareScreenState extends State<LifeMateCompanionCareScreen>{
  late final LifeMateCompanionCareApi _companionApi;late final bool _ownsApi;
  bool _loading=true,_saving=false;String? _error,_patientUserId,_patientName;LifeMateCompanionGuidance? _guidance;
  @override void initState(){super.initState();_ownsApi=widget.companionApi==null;_companionApi=widget.companionApi??LifeMateCompanionCareApi.fromEnvironment();_load();}
  @override void dispose(){if(_ownsApi)_companionApi.close();super.dispose();}

  Future<void> _load()async{if(mounted)setState((){_loading=true;_error=null;_guidance=null;});try{final relationships=await widget.apiClient.getCareRelationships();Map<String,dynamic>? summary;String? patientId,patientName;for(final relationship in relationships){if(relationship['status']?.toString().toLowerCase()!='active')continue;final candidate=relationship['patientUserId']?.toString();if(candidate==null||candidate.isEmpty)continue;try{final value=await widget.apiClient.getCareRecipientWomenCalendar(patientUserId:candidate);summary=value;patientId=candidate;patientName=relationship['patientDisplayName']?.toString();break;}on LifeMateApiException catch(error){if(error.code=='women_calendar_access_denied'||error.code=='women_calendar_not_active')continue;rethrow;}}
    if(summary==null||patientId==null){if(!mounted)return;setState((){_loading=false;_error='locked';});return;}
    final scopes=_map(summary['privacyScopes']);final estimate=_map(summary['estimate']);final shared=_map(summary['latestSharedDailyLog']);final history=(summary['guidanceHistory'] as List<dynamic>???const[]).whereType<Map>().map((x){final m=Map<String,dynamic>.from(x);return LifeMateCompanionGuidanceHistoryItem(guidanceId:m['guidanceId']?.toString()??'',shownAtUtc:DateTime.tryParse(m['shownAtUtc']?.toString()??'')??DateTime.fromMillisecondsSinceEpoch(0,isUtc:true));}).toList(growable:false);final actions=(summary['supportActions'] as List<dynamic>???const[]).whereType<Map>().map((x){final m=Map<String,dynamic>.from(x);return LifeMateCompanionSupportActionHistoryItem(actionType:m['actionType']?.toString()??'',performedAtUtc:DateTime.tryParse(m['performedAtUtc']?.toString()??'')??DateTime.fromMillisecondsSinceEpoch(0,isUtc:true));}).toList(growable:false);
    final selected=const LifeMateCompanionCareEngine().select(phaseAllowed:scopes['viewPhaseSummary']==true,wellbeingAllowed:scopes['viewSharedWellbeing']==true,cycleDay:_int(estimate['cycleDay']),mood:shared['mood']?.toString(),energyLevel:_int(shared['energyLevel']),guidanceHistory:history,supportActions:actions,locale:LifeMateRuntimeLocale.languageCode,nowUtc:DateTime.now().toUtc());
    if(!mounted)return;setState((){_patientUserId=patientId;_patientName=patientName;_guidance=selected;_loading=false;});if(selected!=null){try{await _companionApi.recordImpression(patientUserId:patientId,guidanceId:selected.id,contentVersion:selected.contentVersion,category:selected.category);}on LifeMateApiException catch(error){if(error.code=='women_calendar_access_denied'&&mounted)setState((){_guidance=null;_error='locked';});}}
  }catch(error){if(!mounted)return;setState((){_loading=false;_error=error.toString();});}}

  Future<void> _recordAction()async{final patient=_patientUserId,guidance=_guidance,action=_guidance?.supportActionType;if(patient==null||guidance==null||action==null||_saving)return;setState(()=>_saving=true);try{await widget.apiClient.recordCareRecipientWomenSupportAction(patientUserId:patient,actionType:action);if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(LifeMateRuntimeLocale.select(fa:'همراهی ثبت شد.',en:'Support action recorded.'))));await _load();}on LifeMateApiException catch(error){if(!mounted)return;if(error.code=='women_calendar_access_denied')setState((){_guidance=null;_error='locked';});else ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(LifeMateRuntimeLocale.select(fa:'ثبت همراهی انجام نشد.',en:'Support action could not be recorded.'))));}finally{if(mounted)setState(()=>_saving=false);}}

  @override Widget build(BuildContext context){final fa=LifeMateRuntimeLocale.isPersian;return Scaffold(backgroundColor:widget.background,appBar:AppBar(backgroundColor:widget.background,surfaceTintColor:Colors.transparent,title:Text(fa?'همراهی پیشنهادی':'Support guidance')),body:SafeArea(child:_loading?const Center(child:CircularProgressIndicator()):_error=='locked'?_locked(fa):_error!=null?_failure(fa):_guidance==null?_cooldown(fa):ListView(padding:const EdgeInsets.all(20),children:[Text(_patientName==null?(fa?'همدم من':'My companion'):(fa?'برای $_patientName':'For $_patientName'),style:TextStyle(color:widget.accent,fontWeight:FontWeight.w800)),const SizedBox(height:12),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(26),boxShadow:const [BoxShadow(color:Color(0x10000000),blurRadius:20,offset:Offset(0,8))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.volunteer_activism_rounded,color:widget.accent,size:34),const SizedBox(height:14),Text(_guidance!.title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(_guidance!.message,style:const TextStyle(height:1.65,fontSize:14)),const SizedBox(height:12),Text(fa?'این پیشنهاد تشخیص یا توصیه پزشکی نیست.':'This is supportive guidance, not medical advice.',style:const TextStyle(fontSize:11,color:Colors.black54)),if(_guidance!.supportActionLabel!=null)...[const SizedBox(height:18),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:widget.accent,minimumSize:const Size.fromHeight(52)),onPressed:_saving?null:_recordAction,icon:const Icon(Icons.favorite_outline_rounded),label:Text(_guidance!.supportActionLabel!))]])] )));}
  Widget _locked(bool fa)=>_state(Icons.lock_outline_rounded,fa?'اشتراک‌گذاری لازم خاموش است':'Required sharing is off',fa?'فقط داده‌ای که صاحب حساب صریحاً به اشتراک گذاشته باشد می‌تواند پیشنهاد شخصی‌سازی‌شده بسازد.':'Personalized guidance is available only from explicitly shared data.');
  Widget _cooldown(bool fa)=>_state(Icons.spa_outlined,fa?'فعلاً پیشنهاد تازه‌ای نداریم':'No new suggestion right now',fa?'برای جلوگیری از تکرار و مزاحمت، پیشنهادها فاصله زمانی دارند.':'Guidance uses cooldowns to avoid repetition.');
  Widget _failure(bool fa)=>_state(Icons.cloud_off_rounded,fa?'دریافت پیشنهاد انجام نشد':'Guidance unavailable',fa?'دوباره تلاش کنید.':'Try again.',action:true);
  Widget _state(IconData icon,String title,String message,{bool action=false})=>Center(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:54,color:widget.accent),const SizedBox(height:14),Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text(message,textAlign:TextAlign.center),if(action)...[const SizedBox(height:18),OutlinedButton.icon(onPressed:_load,icon:const Icon(Icons.refresh_rounded),label:Text(LifeMateRuntimeLocale.select(fa:'تلاش دوباره',en:'Retry')))] ])));
  static Map<String,dynamic> _map(dynamic value)=>value is Map?Map<String,dynamic>.from(value):const{};static int? _int(dynamic value)=>value is int?value:int.tryParse(value?.toString()??'');
}
