import 'dart:async';

import 'package:flutter/material.dart';
import 'package:lifemate_client/lifemate_client.dart';

class LifeMateSupportChatScreen extends StatefulWidget {
  const LifeMateSupportChatScreen({super.key, required this.productCode, this.api, this.accent=const Color(0xFF4AAE72), this.background=const Color(0xFFF8FAFC)});
  final String productCode; final LifeMateSupportApi? api; final Color accent, background;
  @override State<LifeMateSupportChatScreen> createState()=>_LifeMateSupportChatScreenState();
}

class _LifeMateSupportChatScreenState extends State<LifeMateSupportChatScreen> with WidgetsBindingObserver {
  late final LifeMateSupportApi _api; late final bool _ownsApi; final _controller=TextEditingController();
  List<LifeMateSupportConversation> _threads=const[]; List<LifeMateSupportMessage> _messages=const[]; String? _ticketId; bool _loading=true,_sending=false; String? _error; Timer? _poll;
  @override void initState(){super.initState();WidgetsBinding.instance.addObserver(this);_ownsApi=widget.api==null;_api=widget.api??LifeMateSupportApi.fromEnvironment();_reload();_poll=Timer.periodic(const Duration(seconds:8),(_)=>_refreshMessages());}
  @override void dispose(){WidgetsBinding.instance.removeObserver(this);_poll?.cancel();_controller.dispose();if(_ownsApi)_api.close();super.dispose();}
  @override void didChangeAppLifecycleState(AppLifecycleState state){if(state==AppLifecycleState.resumed)_reload();}
  Future<void> _reload() async { if(mounted)setState((){_loading=true;_error=null;}); try{final threads=await _api.conversations();final product=threads.where((e)=>e.productCode==widget.productCode).toList();final selected=product.isNotEmpty?product.first:(threads.isNotEmpty?threads.first:null);List<LifeMateSupportMessage> messages=const[];if(selected!=null)messages=await _api.messages(selected.ticketId);if(!mounted)return;setState((){_threads=threads;_ticketId=selected?.ticketId;_messages=messages;_loading=false;});await _markLatestRead();}catch(e){if(!mounted)return;setState((){_error=e.toString();_loading=false;});}}
  Future<void> _refreshMessages() async {final id=_ticketId;if(id==null||_sending)return;try{final items=await _api.messages(id);if(!mounted)return;setState(()=>_messages=items);await _markLatestRead();}catch(_){}}
  Future<void> _markLatestRead() async {final id=_ticketId;if(id==null||_messages.isEmpty)return;final staff=_messages.where((m)=>!m.fromUser).toList();if(staff.isNotEmpty){try{await _api.markRead(id,staff.last.messageId);}catch(_){}}}
  Future<void> _send() async {final text=_controller.text.trim();if(text.isEmpty||_sending)return;setState((){_sending=true;_error=null;});final requestId=LifeMateApiClient.createClientRequestId();try{var id=_ticketId;if(id==null){final opened=await _api.open(productCode:widget.productCode,body:text,clientMessageId:requestId);id=opened['ticketId']?.toString();if(id==null||id.isEmpty)throw const FormatException('Support ticket id missing.');_ticketId=id;}else{await _api.send(id,text,clientMessageId:requestId);}_controller.clear();await _refreshMessages();}catch(e){if(mounted)setState(()=>_error=e.toString());}finally{if(mounted)setState(()=>_sending=false);}}
  @override Widget build(BuildContext context){final fa=Directionality.of(context)==TextDirection.rtl;return Scaffold(backgroundColor:widget.background,appBar:AppBar(title:Text(fa?'پشتیبانی آنلاین':'Online Support'),backgroundColor:widget.background,surfaceTintColor:Colors.transparent),body:SafeArea(child:Column(children:[if(_error!=null)Material(color:Colors.orange.shade50,child:ListTile(leading:const Icon(Icons.cloud_off_rounded),title:Text(fa?'ارتباط با پشتیبانی برقرار نشد':'Support connection failed'),subtitle:Text(fa?'پیام شما پاک نشده؛ دوباره تلاش کنید.':'Your message is preserved. Try again.'),trailing:IconButton(onPressed:_reload,icon:const Icon(Icons.refresh_rounded)))),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):_messages.isEmpty?_empty(fa):RefreshIndicator(onRefresh:_reload,child:ListView.builder(reverse:true,padding:const EdgeInsets.all(16),itemCount:_messages.length,itemBuilder:(context,index){final message=_messages[_messages.length-1-index];return _bubble(message,fa);}))),_composer(fa)])));}
  Widget _empty(bool fa)=>Center(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.support_agent_rounded,size:64,color:widget.accent),const SizedBox(height:16),Text(fa?'چطور می‌توانیم کمک کنیم؟':'How can we help?',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:8),Text(fa?'پیامتان را بفرستید؛ پاسخ پشتیبانی همین‌جا نمایش داده می‌شود.':'Send a message and support replies will appear here.',textAlign:TextAlign.center)])));
  Widget _bubble(LifeMateSupportMessage m,bool fa)=>Align(alignment:m.fromUser?AlignmentDirectional.centerEnd:AlignmentDirectional.centerStart,child:Semantics(label:m.fromUser?(fa?'پیام شما':'Your message'):(fa?'پیام پشتیبانی':'Support message'),child:Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.symmetric(horizontal:14,vertical:11),constraints:const BoxConstraints(maxWidth:330),decoration:BoxDecoration(color:m.fromUser?widget.accent:Colors.white,borderRadius:BorderRadius.circular(18),boxShadow:m.fromUser?null:[const BoxShadow(blurRadius:10,color:Color(0x11000000))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m.body,style:TextStyle(color:m.fromUser?Colors.white:const Color(0xFF1F2937),height:1.45)),if(m.attachments.isNotEmpty)...[const SizedBox(height:8),...m.attachments.map((a)=>Row(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.attach_file_rounded,size:17),Flexible(child:Text(a.fileName,overflow:TextOverflow.ellipsis))]))]]))));
  Widget _composer(bool fa)=>Material(color:Colors.white,elevation:8,child:Padding(padding:const EdgeInsets.fromLTRB(12,10,12,12),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[IconButton(tooltip:fa?'پیوست':'Attachment',onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(fa?'انتخاب فایل امن در مرحله بعدی این صفحه فعال می‌شود.':'Secure file picker is being enabled for this conversation.'))),icon:const Icon(Icons.attach_file_rounded)),Expanded(child:TextField(controller:_controller,minLines:1,maxLines:5,textInputAction:TextInputAction.newline,decoration:InputDecoration(hintText:fa?'پیام به پشتیبانی…':'Message support…',filled:true,fillColor:widget.background,border:OutlineInputBorder(borderRadius:BorderRadius.circular(20),borderSide:BorderSide.none)))),const SizedBox(width:8),IconButton.filled(style:IconButton.styleFrom(backgroundColor:widget.accent),onPressed:_sending?null:_send,icon:_sending?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Icon(Icons.send_rounded))])));
}
